version: '3.8'
services:
  neo4j:
    image: neo4j:5.16.0-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"


